# Generated by Django 5.0.7 on 2024-07-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('tip', models.TextField()),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
